/**
 ******************************************************************************
 * @file    gravity_comp.h
 * @brief   Gravity + friction feed-forward compensation for the
 *          yaw-pitch-pitch field arm.
 *
 * THE DELIVERABLE: a strict 2-input / 2-output static map
 *
 *      input :  q1, q2            (rad, the two pitch motor angles)
 *      output:  tau_c1, tau_c2    (N*m, compensation torque)
 *
 *      tau_c1 = g*(C1*cos q1 + C2*cos(q1+q2)) + g*(S1*sin q1 + S2*sin(q1+q2))
 *      tau_c2 = g*(C3*cos(q1+q2))             + g*(C4*sin(q1+q2))
 *
 * Convention: q = 0 is HORIZONTAL and +q RAISES the link, so the compensation
 * is maximal at q = 0. The C coefficients are the physical static moments
 * (kg*m): C1 = m1*c1 + m2*l1 and C2 = C3 = m2*c2, and they are POSITIVE.
 *
 * There is deliberately NO yaw input: the base yaw axis is collinear with the
 * gravity vector, so it produces zero gravity torque and cannot influence the
 * two pitch joints. That is the whole reason the compensation is 2-in/2-out.
 *
 * The coefficients come from a least-squares fit to logged (q, dq, tau) data,
 * so NO URDF and NO SolidWorks export is required anywhere in this workflow.
 * See docs/design-contract.md for the sign and trig conventions - the classic
 * failure modes here are a reversed compensation sign (system diverges) and a
 * sin/cos swap (torque is wrong by a large factor at most poses).
 *
 * Pure C99, no dynamic memory, no libm beyond sinf/cosf, ~20 lines of work.
 ******************************************************************************
 */

#ifndef ARM_GRAVITY_COMP_H
#define ARM_GRAVITY_COMP_H

#ifdef __cplusplus
extern "C" {
#endif

/** Identified compensation coefficients.
 *
 *  Generated by scripts/export_c_header.py from config/controller.json, so the
 *  MCU and the simulator always run identical numbers. Do not hand-edit the
 *  generated copy.
 *
 *  Units: kg*m (a static moment m*c, not a mass). Cos columns absorb encoder
 *  zero-offset error and are ideally 0.
 */
typedef struct {
  float C1; /* g*cos(q1)    at joint 1 : m1*c1 + m2*l1  (positive) */
  float C2; /* g*cos(q1+q2) at joint 1 : m2*c2          (positive) */
  float C3; /* g*cos(q1+q2) at joint 2 : m2*c2          (positive) */
  float S1; /* g*sin(q1)    at joint 1 : zero-offset term, ~0 */
  float S2; /* g*sin(q1+q2) at joint 1 : zero-offset term, ~0 */
  float C4; /* g*sin(q1+q2) at joint 2 : zero-offset term, ~0 */
} GravityCompParams;

/** Friction / offset feed-forward coefficients: [b1, tc1, o1, b2, tc2, o2].
 *  b = viscous [N*m*s/rad], tc = Coulomb [N*m], o = constant offset [N*m]. */
typedef struct {
  float b1, tc1, o1;
  float b2, tc2, o2;
  float eps; /* tanh smoothing width, rad/s. Must match the fit's eps. */
} GravityCompFriction;

/** Runtime configuration: the two pitch motors' wiring conventions.
 *
 *  These MUST be set from the actual harness. Leaving them wrong is the same
 *  class of bug as getting the sign of the compensation wrong.
 */
typedef struct {
  float q1_zero;  /* rad, encoder reading when link 1 is horizontal */
  float q2_zero;  /* rad, encoder reading when link 2 is horizontal */
  float q1_sign;  /* +1 or -1: does a positive motor angle raise the link? */
  float q2_sign;  /* +1 or -1 */
  float k_grav;   /* 0..1..>1 master scale; 0 disables gravity feed-forward */
  float k_fric;   /* 0 disables friction feed-forward */
  float tau_max;  /* N*m, hard clamp; use DM_T_MAX = 10.0f for a DM-J4310 */
} GravityCompConfig;

/** Default coefficient set, substituted by the generated header. */
extern const GravityCompParams GRAVITY_COMP_PARAMS;
extern const GravityCompFriction GRAVITY_COMP_FRICTION;

/** Initialise runtime config. Call once before the control loop starts.
 *  `q1_zero`/`q2_zero` are the encoder readings with each link horizontal. */
void GravityComp_Init(float q1_zero, float q2_zero, float q1_sign, float q2_sign);

/** Runtime config handle, so the host can tune scaling without recompiling. */
GravityCompConfig *GravityComp_GetConfig(void);

/**
 * @brief  Core compensation: strictly 2 inputs -> 2 outputs.
 * @param  q1, q2   raw motor angles in rad (as read from the encoder)
 * @param  tau1     out, compensation torque for joint 1, N*m
 * @param  tau2     out, compensation torque for joint 2, N*m
 *
 * Applies the zero offsets, the sign convention and the tau_max clamp.
 */
void GravityComp_Calc(float q1, float q2, float *tau1, float *tau2);

/**
 * @brief  Optional friction feed-forward. Needs velocity, so it is kept
 *         separate from the static gravity map.
 * @param  dq1, dq2 joint velocities, rad/s (filtered finite difference)
 */
void GravityComp_FrictionComp(float dq1, float dq2, float *tau1, float *tau2);

/**
 * @brief  Full feed-forward = gravity + friction. Convenience wrapper.
 */
void GravityComp_CalcFull(float q1, float q2, float dq1, float dq2,
                          float *tau1, float *tau2);

/** Worst-case |tau| over the full joint range for the current coefficients.
 *  Use as a commission-time safety check against tau_max. */
float GravityComp_MaxAbsTorque(void);

#ifdef __cplusplus
}
#endif

#endif /* ARM_GRAVITY_COMP_H */
