#pragma once

/* Generated by compute_lqr_and_export.m. */
/* x: [s, s_dot, phi, phi_dot, theta_L, theta_L_dot, theta_R, theta_R_dot, theta_b, theta_b_dot]. */
/* u_mcu: [Tp_R, Tp_L, Tw_R, Tw_L]. */
/* u_model (SJTU): [T_lw_L, T_lw_R, T_bl_L, T_bl_R]. */
/* u_mcu = u0 - K * (x - x_ref). */
/* Model contract: Tp=T_bl (body to leg), Tw=T_lw (motor/leg to wheel). */
/* Tp signs are aligned with the current VMC contract. Positive Tw means the corresponding wheel rolls forward; H6215 command direction still requires hardware calibration. */

/* Fixed 0.170 m design point. The current MCU LQR does not gate on leg length. */
static const float k_double_closed_loop_lqr_fixed_leg_length = 1.700000000e-01f;

static const float k_double_closed_loop_lqr_input_sign[4] = {1.0f, 1.0f, 1.0f, 1.0f};
static const float k_double_closed_loop_lqr_x_ref[10] = {0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f};
static const float k_double_closed_loop_lqr_u0[4] = {0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f};
static const float k_double_closed_loop_lqr_trim_relative_residual = 0.000000000e+00f;

static const float k_double_closed_loop_lqr_nominal[4][10] = {
    {6.349050205e-01f, 6.072988794e-01f, 1.560828963e+00f, 4.859186856e-01f, -1.911573540e+00f, -1.890284921e-01f, 3.396134294e+00f, 3.636960309e-01f, -1.782397615e+01f, -6.095689909e-01f},
    {6.349050205e-01f, 6.072988794e-01f, -1.560828963e+00f, -4.859186856e-01f, 3.396134294e+00f, 3.636960309e-01f, -1.911573540e+00f, -1.890284921e-01f, -1.782397615e+01f, -6.095689909e-01f},
    {-1.796062034e+00f, -1.776496861e+00f, 6.667974974e-01f, 1.858713579e-01f, -1.191682947e+00f, -1.592244016e-01f, -3.781832426e+00f, -4.198826007e-01f, -1.680199121e+00f, -1.122150420e-01f},
    {-1.796062034e+00f, -1.776496861e+00f, -6.667974974e-01f, -1.858713579e-01f, -3.781832426e+00f, -4.198826007e-01f, -1.191682947e+00f, -1.592244016e-01f, -1.680199121e+00f, -1.122150420e-01f}
};
