#pragma once

/* Generated by compute_lqr_and_export.m. */
/* x: [s, s_dot, phi, phi_dot, theta_L, theta_L_dot, theta_R, theta_R_dot, theta_b, theta_b_dot]. */
/* u_mcu: [Tp_R, Tp_L, Tw_R, Tw_L]. */
/* u_mcu = u0 - K * (x - x_ref). */
/* Tp signs are aligned with the current VMC contract. Positive Tw means the corresponding wheel rolls forward; H6215 command direction still requires hardware calibration. */

/* Fixed 0.160 m design point. The current shadow LQR does not gate on leg length. */
static const float k_double_closed_loop_lqr_fixed_leg_length = 1.600000000e-01f;

static const float k_double_closed_loop_lqr_input_sign[4] = {-1.0f, -1.0f, 1.0f, 1.0f};
static const float k_double_closed_loop_lqr_x_ref[10] = {0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f};
static const float k_double_closed_loop_lqr_u0[4] = {0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f};
static const float k_double_closed_loop_lqr_trim_relative_residual = 0.000000000e+00f;

static const float k_double_closed_loop_lqr_nominal[4][10] = {
    {-3.757096370e-01f, -2.847141052e-01f, -1.080644846e+00f, -4.708495224e-01f, 1.026920640e+00f, 1.114069709e-01f, -1.596089526e+00f, -1.270335676e-01f, -1.273918143e+01f, -3.660423856e-01f},
    {-3.757096370e-01f, -2.847141052e-01f, 1.080644846e+00f, 4.708495224e-01f, -1.596089526e+00f, -1.270335676e-01f, 1.026920640e+00f, 1.114069709e-01f, -1.273918143e+01f, -3.660423856e-01f},
    {-7.031029019e+00f, -5.559175059e+00f, 5.030272248e-01f, 1.491069050e-01f, -9.454315068e-01f, 1.207989128e-01f, -1.101585160e+01f, -5.254184395e-01f, 2.722920482e+00f, 1.677130995e-01f},
    {-7.031029019e+00f, -5.559175059e+00f, -5.030272248e-01f, -1.491069050e-01f, -1.101585160e+01f, -5.254184395e-01f, -9.454315068e-01f, 1.207989128e-01f, 2.722920482e+00f, 1.677130995e-01f}
};
